# server
server.port: 80
server.host: localhost

# database
spring.datasource.driver-class-name: org.mariadb.jdbc.Driver
spring.datasource.url: jdbc:mariadb://localhost:3306/zogioddae
spring.datasource.username: root
spring.datasource.password: root

# jpa
spring.jpa.hibernate.ddl-auto: create
spring.jpa.show-sql: true


# redis
spring.redis.host: localhost
spring.redis.port: 6379 

# JavaMailSender
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: ${mail.username}
spring.mail.password: ${mail.password}
#spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

# swagger
spring.mvc.pathmatch.matching-strategy: ant-path-matcher

# Kakao
spring.security.oauth2.client.registration.kakao.client-id: 29c442a730e457501b0132bb9c71cc57
spring.security.oauth2.client.registration.kakao.client-secret: VWcpeMygLZ71RPljyRtaKZX1UnCwQmuE
spring.security.oauth2.client.registration.kakao.scope: profile_nickname, account_email
spring.security.oauth2.client.registration.kakao.client-name: Kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type: authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri: http://localhost/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.client-authentication-method: POST

spring.security.oauth2.client.provider.kakao.authorization-uri: https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri: https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri: https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute: id